environment:
  NuGetApiKey:
    secure: C8lr2mm4fyrXiqkYDZAVosF/1Ufy2hZxQvNaqehHn3zLiN3SXs/gHXzLiPoOByA

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

test_script:
  - ps: Build.ps1